/**
 * VERSION: 1.0
 * JS
 * AUTHOR: Ian Duff
 * EMAIL: ian.duff@essemble.co.uk
 * COPYRIGHT: Essemble Ltd
 * All code © 2016 Essemble Ltd. All rights reserved.
 * This code is the property of Essemble Ltd and cannot be copied, reused or redistributed without prior permission from the author
 **/
function Bats(t) { if (this._colony = [], this._container = document.body, this._number = 20, this._width = $(document).width() - 50, this._height = $(document).height() - 50, this._speed = 3, this._scale = 80, this._src = "lib/assets/bat.gif", this._scare = !1, this._remove = !1, t.container) { var e = document.getElementById(t.container); e && (this._container = e) } t.number && (this._number = t.number), t.width && (this._width = t.width), t.height && (this._height = t.height), t.src && (this._src = t.src), t.speed && (this._speed = t.speed), t.scale && (this._scale = t.scale), t.scare && (this._scare = Boolean(t.scare)), t.remove && (this._remove = Boolean(t.remove)) } Bats.prototype = { init: function () { this.removeAll(); for (var t = 0; t < this._number; t++) { var e = document.createElement("img"); e.src = this._src, e.id = "bat" + t, $(e).css("position", "absolute"), $(e).css("z-index", "906"), $(e).css("left", this._width / 2), $(e).css("top", this._height / 2), $(e).css("width", 0), this._scare && $(e).on("mouseover", this.scare.bind(this, e)), this._remove && $(e).on("click", this.remove.bind(this, e)), this._container.appendChild(e), this._colony.push(e) } this.ready() }, ready: function () { for (var t = 0; t < this._colony.length; t++) { var e = this._colony[t]; this.fly(e, 4e3 * Math.random()) } }, fly: function (t, e) { var i = Math.random() * this._width, s = Math.random() * this._height; $(t).data("left-target", i), i < $(t).position().left ? $(t).css("transform", "scale(-1, 1) rotate(" + 50 * Math.random() + "deg)") : $(t).css("transform", "scale(1, 1) rotate(" + 50 * Math.random() + "deg)"); var o = this, a = Math.random() * this._scale, n = { width: a, left: i, top: s }; $(t).delay(e).animate(n, { duration: (1e3 + Math.random()) * this._speed, easing: "easeInOutSine", complete: function () { o.fly(t, 0) } }) }, scare: function (t) { var e = this, i = $(t).position().left + 100; if ($(t).position().left > $(t).data("left-target")) var i = $(t).position().left - 100; var s = Math.random() * (this._scale / 2), o = { width: s, left: i }; $(t).stop().animate(o, { duration: 700, easing: "easeOutQuad", complete: function () { e.fly(t, 0) } }) }, remove: function (t) { var e = $(t).position().left + 100; if ($(t).position().left > $(t).data("left-target")) var e = $(t).position().left - 100; var i = 0, s = { width: i, left: e }; $(t).stop().animate(s, { duration: 700, easing: "easeOutQuad", complete: function () { $(t).remove() } }) }, removeAll: function () { for (var t = 0; t < this._colony.length; t++) { var e = this._colony[t]; $(e).stop().remove() } this._colony = [] } };